spring_profiles: postgresql,default

encryption:
  active_key_label: CHANGE-THIS-KEY
  encryption_keys:
  - label: CHANGE-THIS-KEY
    passphrase: CHANGEME
# Default token signing key. Each installation MUST provide a unique key
# in order for tokens to be usable only on that installation.
#
jwt:
  token:
    verification-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx4DV2R7rcNVB6xvblWz2
      rvEygw437gwy0c7FUHVjtJPhdhLbhcjufMM0s7geKMVCcu01bsOlxSMJJwj5ALo7
      If/po/pbCRc6GiQHlIVyZHozvvM57GT6dUYbyWgIKVrs5Nlv8sEjk6ynvdkRJo5k
      2ZSpFXE7CWMezfwQrlmTU4i6QCbXy1WRcmJ9HqeUJZ+J6fdNx/k1XQsxWWoUiD+q
      RtwcFwK1FAhhp9Un/RthtobxlrMLexRDxfqb4hANV+fJHngUhXRfi3mR7mWasrU+
      pRbUnZSZR0zu8jdCFqH3tGzxfGK2mGQGRhJO3PJzR/ZpuRKNBgmdLwPgPYQ9lcIR
      owIDAQAB
      -----END PUBLIC KEY-----
    signing-key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEAx4DV2R7rcNVB6xvblWz2rvEygw437gwy0c7FUHVjtJPhdhLb
      hcjufMM0s7geKMVCcu01bsOlxSMJJwj5ALo7If/po/pbCRc6GiQHlIVyZHozvvM5
      7GT6dUYbyWgIKVrs5Nlv8sEjk6ynvdkRJo5k2ZSpFXE7CWMezfwQrlmTU4i6QCbX
      y1WRcmJ9HqeUJZ+J6fdNx/k1XQsxWWoUiD+qRtwcFwK1FAhhp9Un/RthtobxlrML
      exRDxfqb4hANV+fJHngUhXRfi3mR7mWasrU+pRbUnZSZR0zu8jdCFqH3tGzxfGK2
      mGQGRhJO3PJzR/ZpuRKNBgmdLwPgPYQ9lcIRowIDAQABAoIBAASeMdUFxzNkbFMx
      4OJTlF42TRIFiTvkYmTC4YRcQ0ORzL078ILnRMX0isrCL0iIUGJypTL8KmEmz3Zs
      2b6vkODXmKPoDqVmOT0Tqm1ArYYv4fTAko2rRLTkO45s7wtuBF/DvLikydsIOxXE
      6YW39BOpQkSxy0kLV1IzTHuMrUFYtWhLRPmIoe/rJQgs3r4urAL956MZnuraCOLl
      qZdUF92pU32e0tIuBvK80Ce1lNHgUXnuD5MLK4Juwsj/ViOkTuaeClQTtEyuM9Lq
      5WKhuOYP0s4O0K0sikpfCT64tFrcyYuH0sBMdCCUgkYRUHJ71YM8BzfcvcRjxYWr
      FjuF8/kCgYEA5XGE1/01t9MZuo3+/EEENGLQIMZnhO25k7UPSMzVL1skzyBQDOmE
      99yM2o+xBNrMzwLTtb0qo2hjArQEsuCaihtppxBz3jYvqcgryIgGmWJidFCj7KRw
      jMeEu//l7DV7tkGxwo4YfDWJQ7XaM7FUwA2qQWSr2KkEpd9npjxq9ecCgYEA3pgu
      BRHccA7RHyg3X4Uw0UgNlnoEGf7ElODYRDlcGm9P1CUNX0ODuqrAz54Ppwhsctza
      L+xc9f2xt+8UGwSkZoNRxQVH/lClyu9CYFZfEqZRAKMRoFGnUPgEGMbsIH6Ur3J8
      l4rZ5VrZOfgU9Ibj0KPkFaXCvsOAVvtJqlCz1uUCgYAZVF3pBlAe2hQ2DyT+LiNL
      sTju1VhqSWA6WTu1ur8yOiqnHxcXRdRjFJsMKd7N/WWs2NAMeTSy03xSuRLnuHn3
      Ey2nvt47wtmiMbH7smCgIEdkNd7S6hhuwjv6ETcNy527sibwpoU3eSWNLw9Gs6X6
      iceo7nc2NPqJYU9s/7CDMwKBgFHeVs62iwUL7g4vlG4lZpcSkSzPI8ML2PGI4QH2
      ttFiL1IvboOjKUf2lYPG9qrQhlKYuAb4QBiZfkvQOuzVAEJT+jckgh4fO1swNJGK
      Mt2BHjnFwC3e2lMFZTxXrXEmHTmKOhjikNGyYELZ45ssIY4TOUhc9wuCjClxst5Z
      YEuhAoGAYQ4NP4yXiKNPfMY1GS0eQOp9GwEEi8UIKrvLaiDH657VlvNcKE5obOdQ
      JwxjMk67tMmnHG2Kuzv0TNIa6QOXohZaRVdEj2w6kq1jBKPWPKMy01vqaKqDt8db
      uZJgVyqobR9IAP91z8l8xJgcIvOhy9r+JFEuaas7hIwEWWMeaaI=
      -----END RSA PRIVATE KEY-----
    claims:
      exclude:
        - authorities
    policy:
      # Will override global validity policies for the default zone only.
      accessTokenValiditySeconds: 3600
      refreshTokenValiditySeconds: 3600
      activeKeyId: key-id-1
      keys:
        key-id-1:
          signingKey: |
                    -----BEGIN RSA PRIVATE KEY-----
                    MIIEogIBAAKCAQEAx4DV2R7rcNVB6xvblWz2rvEygw437gwy0c7FUHVjtJPhdhLb
                    hcjufMM0s7geKMVCcu01bsOlxSMJJwj5ALo7If/po/pbCRc6GiQHlIVyZHozvvM5
                    7GT6dUYbyWgIKVrs5Nlv8sEjk6ynvdkRJo5k2ZSpFXE7CWMezfwQrlmTU4i6QCbX
                    y1WRcmJ9HqeUJZ+J6fdNx/k1XQsxWWoUiD+qRtwcFwK1FAhhp9Un/RthtobxlrML
                    exRDxfqb4hANV+fJHngUhXRfi3mR7mWasrU+pRbUnZSZR0zu8jdCFqH3tGzxfGK2
                    mGQGRhJO3PJzR/ZpuRKNBgmdLwPgPYQ9lcIRowIDAQABAoIBAASeMdUFxzNkbFMx
                    4OJTlF42TRIFiTvkYmTC4YRcQ0ORzL078ILnRMX0isrCL0iIUGJypTL8KmEmz3Zs
                    2b6vkODXmKPoDqVmOT0Tqm1ArYYv4fTAko2rRLTkO45s7wtuBF/DvLikydsIOxXE
                    6YW39BOpQkSxy0kLV1IzTHuMrUFYtWhLRPmIoe/rJQgs3r4urAL956MZnuraCOLl
                    qZdUF92pU32e0tIuBvK80Ce1lNHgUXnuD5MLK4Juwsj/ViOkTuaeClQTtEyuM9Lq
                    5WKhuOYP0s4O0K0sikpfCT64tFrcyYuH0sBMdCCUgkYRUHJ71YM8BzfcvcRjxYWr
                    FjuF8/kCgYEA5XGE1/01t9MZuo3+/EEENGLQIMZnhO25k7UPSMzVL1skzyBQDOmE
                    99yM2o+xBNrMzwLTtb0qo2hjArQEsuCaihtppxBz3jYvqcgryIgGmWJidFCj7KRw
                    jMeEu//l7DV7tkGxwo4YfDWJQ7XaM7FUwA2qQWSr2KkEpd9npjxq9ecCgYEA3pgu
                    BRHccA7RHyg3X4Uw0UgNlnoEGf7ElODYRDlcGm9P1CUNX0ODuqrAz54Ppwhsctza
                    L+xc9f2xt+8UGwSkZoNRxQVH/lClyu9CYFZfEqZRAKMRoFGnUPgEGMbsIH6Ur3J8
                    l4rZ5VrZOfgU9Ibj0KPkFaXCvsOAVvtJqlCz1uUCgYAZVF3pBlAe2hQ2DyT+LiNL
                    sTju1VhqSWA6WTu1ur8yOiqnHxcXRdRjFJsMKd7N/WWs2NAMeTSy03xSuRLnuHn3
                    Ey2nvt47wtmiMbH7smCgIEdkNd7S6hhuwjv6ETcNy527sibwpoU3eSWNLw9Gs6X6
                    iceo7nc2NPqJYU9s/7CDMwKBgFHeVs62iwUL7g4vlG4lZpcSkSzPI8ML2PGI4QH2
                    ttFiL1IvboOjKUf2lYPG9qrQhlKYuAb4QBiZfkvQOuzVAEJT+jckgh4fO1swNJGK
                    Mt2BHjnFwC3e2lMFZTxXrXEmHTmKOhjikNGyYELZ45ssIY4TOUhc9wuCjClxst5Z
                    YEuhAoGAYQ4NP4yXiKNPfMY1GS0eQOp9GwEEi8UIKrvLaiDH657VlvNcKE5obOdQ
                    JwxjMk67tMmnHG2Kuzv0TNIa6QOXohZaRVdEj2w6kq1jBKPWPKMy01vqaKqDt8db
                    uZJgVyqobR9IAP91z8l8xJgcIvOhy9r+JFEuaas7hIwEWWMeaaI=
                    -----END RSA PRIVATE KEY-----
      # Sets the default validity for all zones
      global:
        accessTokenValiditySeconds: 3600
        refreshTokenValiditySeconds: 3600
    # This is a feature flag to turn on/off the refresh token issuance behavior. If set to true, the refresh token is only granted to clients with a scope of refresh_token for offline access.
    refresh:
      restrict_grant: true
      unique: false
      format: jwt

login:
  serviceProviderKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIICXQIBAAKBgQDHtC5gUXxBKpEqZTLkNvFwNGnNIkggNOwOQVNbpO0WVHIivig5
    L39WqS9u0hnA+O7MCA/KlrAR4bXaeVVhwfUPYBKIpaaTWFQR5cTR1UFZJL/OF9vA
    fpOwznoD66DDCnQVpbCjtDYWX+x6imxn8HCYxhMol6ZnTbSsFW6VZjFMjQIDAQAB
    AoGAVOj2Yvuigi6wJD99AO2fgF64sYCm/BKkX3dFEw0vxTPIh58kiRP554Xt5ges
    7ZCqL9QpqrChUikO4kJ+nB8Uq2AvaZHbpCEUmbip06IlgdA440o0r0CPo1mgNxGu
    lhiWRN43Lruzfh9qKPhleg2dvyFGQxy5Gk6KW/t8IS4x4r0CQQD/dceBA+Ndj3Xp
    ubHfxqNz4GTOxndc/AXAowPGpge2zpgIc7f50t8OHhG6XhsfJ0wyQEEvodDhZPYX
    kKBnXNHzAkEAyCA76vAwuxqAd3MObhiebniAU3SnPf2u4fdL1EOm92dyFs1JxyyL
    gu/DsjPjx6tRtn4YAalxCzmAMXFSb1qHfwJBAM3qx3z0gGKbUEWtPHcP7BNsrnWK
    vw6By7VC8bk/ffpaP2yYspS66Le9fzbFwoDzMVVUO/dELVZyBnhqSRHoXQcCQQCe
    A2WL8S5o7Vn19rC0GVgu3ZJlUrwiZEVLQdlrticFPXaFrn3Md82ICww3jmURaKHS
    N+l4lnMda79eSp3OMmq9AkA0p79BvYsLshUJJnvbk76pCjR28PK4dV1gSDUEqQMB
    qy45ptdwJLqLJCeNoR0JUcDNIRhOCuOPND7pcMtX6hI/
    -----END RSA PRIVATE KEY-----
  serviceProviderKeyPassword: password
  serviceProviderCertificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSTCCArKgAwIBAgIBADANBgkqhkiG9w0BAQQFADB8MQswCQYDVQQGEwJhdzEO
    MAwGA1UECBMFYXJ1YmExDjAMBgNVBAoTBWFydWJhMQ4wDAYDVQQHEwVhcnViYTEO
    MAwGA1UECxMFYXJ1YmExDjAMBgNVBAMTBWFydWJhMR0wGwYJKoZIhvcNAQkBFg5h
    cnViYUBhcnViYS5hcjAeFw0xNTExMjAyMjI2MjdaFw0xNjExMTkyMjI2MjdaMHwx
    CzAJBgNVBAYTAmF3MQ4wDAYDVQQIEwVhcnViYTEOMAwGA1UEChMFYXJ1YmExDjAM
    BgNVBAcTBWFydWJhMQ4wDAYDVQQLEwVhcnViYTEOMAwGA1UEAxMFYXJ1YmExHTAb
    BgkqhkiG9w0BCQEWDmFydWJhQGFydWJhLmFyMIGfMA0GCSqGSIb3DQEBAQUAA4GN
    ADCBiQKBgQDHtC5gUXxBKpEqZTLkNvFwNGnNIkggNOwOQVNbpO0WVHIivig5L39W
    qS9u0hnA+O7MCA/KlrAR4bXaeVVhwfUPYBKIpaaTWFQR5cTR1UFZJL/OF9vAfpOw
    znoD66DDCnQVpbCjtDYWX+x6imxn8HCYxhMol6ZnTbSsFW6VZjFMjQIDAQABo4Ha
    MIHXMB0GA1UdDgQWBBTx0lDzjH/iOBnOSQaSEWQLx1syGDCBpwYDVR0jBIGfMIGc
    gBTx0lDzjH/iOBnOSQaSEWQLx1syGKGBgKR+MHwxCzAJBgNVBAYTAmF3MQ4wDAYD
    VQQIEwVhcnViYTEOMAwGA1UEChMFYXJ1YmExDjAMBgNVBAcTBWFydWJhMQ4wDAYD
    VQQLEwVhcnViYTEOMAwGA1UEAxMFYXJ1YmExHTAbBgkqhkiG9w0BCQEWDmFydWJh
    QGFydWJhLmFyggEAMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEEBQADgYEAYvBJ
    0HOZbbHClXmGUjGs+GS+xC1FO/am2suCSYqNB9dyMXfOWiJ1+TLJk+o/YZt8vuxC
    KdcZYgl4l/L6PxJ982SRhc83ZW2dkAZI4M0/Ud3oePe84k8jm3A7EvH5wi5hvCkK
    RpuRBwn3Ei+jCRouxTbzKPsuCVB+1sNyxMTXzf0=
    -----END CERTIFICATE-----
#The secret that an external login server will use to authenticate to the uaa using the id `login`
LOGIN_SECRET: loginsecret

jwt:
  token:
    signing-key: tokenKey
database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://db:${DB_PORT_5432_TCP_PORT:5432}/${DB_ENV_DB:postgres}
  username: ${DB_ENV_USER:postgres}
  password: ${DB_ENV_PASS:postgres}

oauth:
  client:
    override: true
    autoapprove:
      - test
  clients:
    test:
      id: test
      secret: test
      authorized-grant-types: client_credentials
      scope: scim.read,scim.write,password.write,cloud_controller.admin,uaa.admin
      authorities: uaa.resource,scim.write,scim.read,password.write,cloud_controller.admin,uaa.admin


scim:
  username_pattern: '[a-z0-9+\-_.@]+'
  users:
    - testy|testy|testy|testy|testy|openid,scim.write,scim.read,password.write,cloud_controller.admin,uaa.admin
